<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['mail_antispam_app_description'] = 'Приложение "Антиспам почты" предоставляет почтовый фильтр, который использует широкий диапазон эвристических тестов, чтобы идентифицировать спам.';
$lang['mail_antispam_app_name'] = 'Антиспам почты';
$lang['mail_antispam_blacklist'] = 'Черный список';
$lang['mail_antispam_list'] = 'Список (один email в строке)';
$lang['mail_antispam_lists'] = 'Список';
$lang['mail_antispam_whitelist'] = 'Белый список';
