#!/bin/sh

if [ -e /etc/sysconfig/sa-update ]; then
    CHECK=`grep ^SAUPDATE /etc/sysconfig/sa-update 2>/dev/null`
    if [ -z "$CHECK" ]; then
        logger -p local6.notice -t installer "app-mail-antispam-core - updating antispam update policy"
        sed -i -e 's/^#SAUPDATE=yes.*/SAUPDATE=yes/' /etc/sysconfig/sa-update
    fi
    CHECK=`grep ^SAUPDATE /etc/sysconfig/sa-update 2>/dev/null`
    if [ -z "$CHECK" ]; then
        logger -p local6.notice -t installer "app-mail-antispam-core - adding antispam update policy"
        echo "SAUPDATE=yes" >> /etc/sysconfig/sa-update
    fi
fi
