<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['mail_antispam_app_description'] = 'Aplikacja Antispam dostarcza filtr wiadomości, który korzysta z szerokiego zakresu testów heurystycznych do identyfikacji spamu.';
$lang['mail_antispam_app_name'] = 'Antispam pocztowy';
$lang['mail_antispam_blacklist'] = 'Czarna lista';
$lang['mail_antispam_list'] = 'Lista (jeden email w linii)';
$lang['mail_antispam_lists'] = 'Listy';
$lang['mail_antispam_whitelist'] = 'Biała lista';
